name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can use any version of Node.js you're working with

      - name: Install dependencies
        run: |
          npm install

      - name: Build the React app
        run: |
          npm run build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-north-1'  # Replace with your AWS region7

      - name: Sync files to S3
        run: |
          aws s3 sync ./build/ s3://your-s3-bucket-name --delete  # Removed the --acl public-read flag
